# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteo_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 772)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameFiltro = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameFiltro.sizePolicy().hasHeightForWidth())
        self.frameFiltro.setSizePolicy(sizePolicy)
        self.frameFiltro.setObjectName("frameFiltro")
        self.layoutFiltro = QtWidgets.QHBoxLayout(self.frameFiltro)
        self.layoutFiltro.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layoutFiltro.setContentsMargins(100, -1, 100, -1)
        self.layoutFiltro.setSpacing(20)
        self.layoutFiltro.setObjectName("layoutFiltro")
        self.labelFiltro = QtWidgets.QLabel(self.frameFiltro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFiltro.sizePolicy().hasHeightForWidth())
        self.labelFiltro.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelFiltro.setFont(font)
        self.labelFiltro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFiltro.setObjectName("labelFiltro")
        self.layoutFiltro.addWidget(self.labelFiltro)
        self.lineEditFiltro = QtWidgets.QLineEdit(self.frameFiltro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFiltro.sizePolicy().hasHeightForWidth())
        self.lineEditFiltro.setSizePolicy(sizePolicy)
        self.lineEditFiltro.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEditFiltro.setMaxLength(100)
        self.lineEditFiltro.setObjectName("lineEditFiltro")
        self.layoutFiltro.addWidget(self.lineEditFiltro)
        self.pushButtonFiltro = QtWidgets.QPushButton(self.frameFiltro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFiltro.sizePolicy().hasHeightForWidth())
        self.pushButtonFiltro.setSizePolicy(sizePolicy)
        self.pushButtonFiltro.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButtonFiltro.setObjectName("pushButtonFiltro")
        self.layoutFiltro.addWidget(self.pushButtonFiltro)
        self.listWidgetFiltro = QtWidgets.QListWidget(self.frameFiltro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetFiltro.sizePolicy().hasHeightForWidth())
        self.listWidgetFiltro.setSizePolicy(sizePolicy)
        self.listWidgetFiltro.setMinimumSize(QtCore.QSize(250, 80))
        self.listWidgetFiltro.setMaximumSize(QtCore.QSize(250, 80))
        self.listWidgetFiltro.setObjectName("listWidgetFiltro")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetFiltro.addItem(item)
        self.layoutFiltro.addWidget(self.listWidgetFiltro)
        self.verticalLayout.addWidget(self.frameFiltro)
        self.framePoblacion = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePoblacion.sizePolicy().hasHeightForWidth())
        self.framePoblacion.setSizePolicy(sizePolicy)
        self.framePoblacion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePoblacion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePoblacion.setObjectName("framePoblacion")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.framePoblacion)
        self.verticalLayout_2.setContentsMargins(6, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelPoblacion = QtWidgets.QLabel(self.framePoblacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPoblacion.sizePolicy().hasHeightForWidth())
        self.labelPoblacion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelPoblacion.setFont(font)
        self.labelPoblacion.setObjectName("labelPoblacion")
        self.verticalLayout_2.addWidget(self.labelPoblacion)
        self.pushButtonPoblacion = QtWidgets.QPushButton(self.framePoblacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPoblacion.sizePolicy().hasHeightForWidth())
        self.pushButtonPoblacion.setSizePolicy(sizePolicy)
        self.pushButtonPoblacion.setObjectName("pushButtonPoblacion")
        self.verticalLayout_2.addWidget(self.pushButtonPoblacion)
        self.verticalLayout.addWidget(self.framePoblacion)
        self.framePrediccion = QtWidgets.QFrame(self.centralwidget)
        self.framePrediccion.setStyleSheet("")
        self.framePrediccion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framePrediccion.setObjectName("framePrediccion")
        self.gridLayout = QtWidgets.QGridLayout(self.framePrediccion)
        self.gridLayout.setObjectName("gridLayout")
        self.frameCielo13 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo13.setObjectName("frameCielo13")
        self.verticalLayoutCielo13 = QtWidgets.QVBoxLayout(self.frameCielo13)
        self.verticalLayoutCielo13.setObjectName("verticalLayoutCielo13")
        self.labelHora13 = QtWidgets.QLabel(self.frameCielo13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora13.setFont(font)
        self.labelHora13.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora13.setObjectName("labelHora13")
        self.verticalLayoutCielo13.addWidget(self.labelHora13)
        self.labelCielo13 = QtWidgets.QLabel(self.frameCielo13)
        self.labelCielo13.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo13.setText("")
        self.labelCielo13.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo13.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo13.setObjectName("labelCielo13")
        self.verticalLayoutCielo13.addWidget(self.labelCielo13)
        self.labelTemp13 = QtWidgets.QLabel(self.frameCielo13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp13.setFont(font)
        self.labelTemp13.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp13.setObjectName("labelTemp13")
        self.verticalLayoutCielo13.addWidget(self.labelTemp13)
        self.gridLayout.addWidget(self.frameCielo13, 1, 2, 1, 1)
        self.frameCielo12 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo12.setObjectName("frameCielo12")
        self.verticalLayoutCielo12 = QtWidgets.QVBoxLayout(self.frameCielo12)
        self.verticalLayoutCielo12.setObjectName("verticalLayoutCielo12")
        self.labelHora12 = QtWidgets.QLabel(self.frameCielo12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora12.setFont(font)
        self.labelHora12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora12.setObjectName("labelHora12")
        self.verticalLayoutCielo12.addWidget(self.labelHora12)
        self.labelCielo12 = QtWidgets.QLabel(self.frameCielo12)
        self.labelCielo12.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo12.setText("")
        self.labelCielo12.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo12.setObjectName("labelCielo12")
        self.verticalLayoutCielo12.addWidget(self.labelCielo12)
        self.labelTemp12 = QtWidgets.QLabel(self.frameCielo12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp12.setFont(font)
        self.labelTemp12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp12.setObjectName("labelTemp12")
        self.verticalLayoutCielo12.addWidget(self.labelTemp12)
        self.gridLayout.addWidget(self.frameCielo12, 1, 1, 1, 1)
        self.frameCielo11 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo11.setObjectName("frameCielo11")
        self.verticalLayoutCielo11 = QtWidgets.QVBoxLayout(self.frameCielo11)
        self.verticalLayoutCielo11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayoutCielo11.setObjectName("verticalLayoutCielo11")
        self.labelHora11 = QtWidgets.QLabel(self.frameCielo11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelHora11.setFont(font)
        self.labelHora11.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora11.setObjectName("labelHora11")
        self.verticalLayoutCielo11.addWidget(self.labelHora11)
        self.labelCielo11 = QtWidgets.QLabel(self.frameCielo11)
        self.labelCielo11.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo11.setToolTip("")
        self.labelCielo11.setLineWidth(1)
        self.labelCielo11.setMidLineWidth(0)
        self.labelCielo11.setText("")
        self.labelCielo11.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo11.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo11.setObjectName("labelCielo11")
        self.verticalLayoutCielo11.addWidget(self.labelCielo11)
        self.labelTemp11 = QtWidgets.QLabel(self.frameCielo11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp11.setFont(font)
        self.labelTemp11.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp11.setObjectName("labelTemp11")
        self.verticalLayoutCielo11.addWidget(self.labelTemp11)
        self.gridLayout.addWidget(self.frameCielo11, 1, 0, 1, 1)
        self.frameCielo23 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo23.setObjectName("frameCielo23")
        self.verticalLayoutCielo23 = QtWidgets.QVBoxLayout(self.frameCielo23)
        self.verticalLayoutCielo23.setObjectName("verticalLayoutCielo23")
        self.labelHora23 = QtWidgets.QLabel(self.frameCielo23)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora23.setFont(font)
        self.labelHora23.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora23.setObjectName("labelHora23")
        self.verticalLayoutCielo23.addWidget(self.labelHora23)
        self.labelCielo23 = QtWidgets.QLabel(self.frameCielo23)
        self.labelCielo23.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo23.setText("")
        self.labelCielo23.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo23.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo23.setObjectName("labelCielo23")
        self.verticalLayoutCielo23.addWidget(self.labelCielo23)
        self.labelTemp23 = QtWidgets.QLabel(self.frameCielo23)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp23.setFont(font)
        self.labelTemp23.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp23.setObjectName("labelTemp23")
        self.verticalLayoutCielo23.addWidget(self.labelTemp23)
        self.gridLayout.addWidget(self.frameCielo23, 1, 6, 1, 1)
        self.frameCielo31 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo31.setObjectName("frameCielo31")
        self.verticalLayoutCielo31 = QtWidgets.QVBoxLayout(self.frameCielo31)
        self.verticalLayoutCielo31.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayoutCielo31.setObjectName("verticalLayoutCielo31")
        self.labelHora31 = QtWidgets.QLabel(self.frameCielo31)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora31.setFont(font)
        self.labelHora31.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora31.setObjectName("labelHora31")
        self.verticalLayoutCielo31.addWidget(self.labelHora31)
        self.labelCielo31 = QtWidgets.QLabel(self.frameCielo31)
        self.labelCielo31.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo31.setToolTip("")
        self.labelCielo31.setText("")
        self.labelCielo31.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo31.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo31.setObjectName("labelCielo31")
        self.verticalLayoutCielo31.addWidget(self.labelCielo31)
        self.labelTemp31 = QtWidgets.QLabel(self.frameCielo31)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp31.setFont(font)
        self.labelTemp31.setText("")
        self.labelTemp31.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp31.setObjectName("labelTemp31")
        self.verticalLayoutCielo31.addWidget(self.labelTemp31)
        self.gridLayout.addWidget(self.frameCielo31, 1, 8, 1, 1)
        self.labelCota51 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota51.setFont(font)
        self.labelCota51.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota51.setObjectName("labelCota51")
        self.gridLayout.addWidget(self.labelCota51, 5, 12, 1, 1)
        self.labelCota32 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota32.setFont(font)
        self.labelCota32.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota32.setObjectName("labelCota32")
        self.gridLayout.addWidget(self.labelCota32, 5, 9, 1, 1)
        self.frameCielo41 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo41.setObjectName("frameCielo41")
        self.verticalLayoutCielo41 = QtWidgets.QVBoxLayout(self.frameCielo41)
        self.verticalLayoutCielo41.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayoutCielo41.setObjectName("verticalLayoutCielo41")
        self.labelHora41 = QtWidgets.QLabel(self.frameCielo41)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora41.setFont(font)
        self.labelHora41.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora41.setObjectName("labelHora41")
        self.verticalLayoutCielo41.addWidget(self.labelHora41)
        self.labelCielo41 = QtWidgets.QLabel(self.frameCielo41)
        self.labelCielo41.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo41.setToolTip("")
        self.labelCielo41.setText("")
        self.labelCielo41.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo41.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo41.setObjectName("labelCielo41")
        self.verticalLayoutCielo41.addWidget(self.labelCielo41)
        self.labelTemp41 = QtWidgets.QLabel(self.frameCielo41)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp41.setFont(font)
        self.labelTemp41.setText("")
        self.labelTemp41.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp41.setObjectName("labelTemp41")
        self.verticalLayoutCielo41.addWidget(self.labelTemp41)
        self.gridLayout.addWidget(self.frameCielo41, 1, 10, 1, 1)
        self.frameCielo14 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo14.setObjectName("frameCielo14")
        self.verticalLayoutCielo14 = QtWidgets.QVBoxLayout(self.frameCielo14)
        self.verticalLayoutCielo14.setObjectName("verticalLayoutCielo14")
        self.labelHora14 = QtWidgets.QLabel(self.frameCielo14)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora14.setFont(font)
        self.labelHora14.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora14.setObjectName("labelHora14")
        self.verticalLayoutCielo14.addWidget(self.labelHora14)
        self.labelCielo14 = QtWidgets.QLabel(self.frameCielo14)
        self.labelCielo14.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo14.setText("")
        self.labelCielo14.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo14.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo14.setObjectName("labelCielo14")
        self.verticalLayoutCielo14.addWidget(self.labelCielo14)
        self.labelTemp14 = QtWidgets.QLabel(self.frameCielo14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp14.setFont(font)
        self.labelTemp14.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp14.setObjectName("labelTemp14")
        self.verticalLayoutCielo14.addWidget(self.labelTemp14)
        self.gridLayout.addWidget(self.frameCielo14, 1, 3, 1, 1)
        self.frameCielo71 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo71.setObjectName("frameCielo71")
        self.verticalLayoutCielo61_3 = QtWidgets.QVBoxLayout(self.frameCielo71)
        self.verticalLayoutCielo61_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayoutCielo61_3.setObjectName("verticalLayoutCielo61_3")
        self.labelHora71 = QtWidgets.QLabel(self.frameCielo71)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHora71.setFont(font)
        self.labelHora71.setText("")
        self.labelHora71.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora71.setObjectName("labelHora71")
        self.verticalLayoutCielo61_3.addWidget(self.labelHora71)
        self.labelCielo71 = QtWidgets.QLabel(self.frameCielo71)
        self.labelCielo71.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo71.setToolTip("")
        self.labelCielo71.setText("")
        self.labelCielo71.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo71.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo71.setObjectName("labelCielo71")
        self.verticalLayoutCielo61_3.addWidget(self.labelCielo71)
        self.labelTemp71 = QtWidgets.QLabel(self.frameCielo71)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp71.setFont(font)
        self.labelTemp71.setText("")
        self.labelTemp71.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp71.setObjectName("labelTemp71")
        self.verticalLayoutCielo61_3.addWidget(self.labelTemp71)
        self.gridLayout.addWidget(self.frameCielo71, 1, 14, 1, 1)
        self.frameCielo22 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo22.setObjectName("frameCielo22")
        self.verticalLayoutCielo22 = QtWidgets.QVBoxLayout(self.frameCielo22)
        self.verticalLayoutCielo22.setObjectName("verticalLayoutCielo22")
        self.labelHora22 = QtWidgets.QLabel(self.frameCielo22)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora22.setFont(font)
        self.labelHora22.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora22.setObjectName("labelHora22")
        self.verticalLayoutCielo22.addWidget(self.labelHora22)
        self.labelCielo22 = QtWidgets.QLabel(self.frameCielo22)
        self.labelCielo22.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo22.setText("")
        self.labelCielo22.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo22.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo22.setObjectName("labelCielo22")
        self.verticalLayoutCielo22.addWidget(self.labelCielo22)
        self.labelTemp22 = QtWidgets.QLabel(self.frameCielo22)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp22.setFont(font)
        self.labelTemp22.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp22.setObjectName("labelTemp22")
        self.verticalLayoutCielo22.addWidget(self.labelTemp22)
        self.gridLayout.addWidget(self.frameCielo22, 1, 5, 1, 1)
        self.frameCielo51 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo51.setObjectName("frameCielo51")
        self.verticalLayoutCielo51 = QtWidgets.QVBoxLayout(self.frameCielo51)
        self.verticalLayoutCielo51.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayoutCielo51.setObjectName("verticalLayoutCielo51")
        self.labelHora51 = QtWidgets.QLabel(self.frameCielo51)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHora51.setFont(font)
        self.labelHora51.setText("")
        self.labelHora51.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora51.setObjectName("labelHora51")
        self.verticalLayoutCielo51.addWidget(self.labelHora51)
        self.labelCielo51 = QtWidgets.QLabel(self.frameCielo51)
        self.labelCielo51.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo51.setToolTip("")
        self.labelCielo51.setText("")
        self.labelCielo51.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo51.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo51.setObjectName("labelCielo51")
        self.verticalLayoutCielo51.addWidget(self.labelCielo51)
        self.labelTemp51 = QtWidgets.QLabel(self.frameCielo51)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp51.setFont(font)
        self.labelTemp51.setText("")
        self.labelTemp51.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp51.setObjectName("labelTemp51")
        self.verticalLayoutCielo51.addWidget(self.labelTemp51)
        self.gridLayout.addWidget(self.frameCielo51, 1, 12, 1, 1)
        self.frameCielo61 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo61.setObjectName("frameCielo61")
        self.verticalLayoutCielo61 = QtWidgets.QVBoxLayout(self.frameCielo61)
        self.verticalLayoutCielo61.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayoutCielo61.setObjectName("verticalLayoutCielo61")
        self.labelHora61 = QtWidgets.QLabel(self.frameCielo61)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelHora61.setFont(font)
        self.labelHora61.setText("")
        self.labelHora61.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora61.setObjectName("labelHora61")
        self.verticalLayoutCielo61.addWidget(self.labelHora61)
        self.labelCielo61 = QtWidgets.QLabel(self.frameCielo61)
        self.labelCielo61.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo61.setToolTip("")
        self.labelCielo61.setText("")
        self.labelCielo61.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo61.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo61.setObjectName("labelCielo61")
        self.verticalLayoutCielo61.addWidget(self.labelCielo61)
        self.labelTemp61 = QtWidgets.QLabel(self.frameCielo61)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp61.setFont(font)
        self.labelTemp61.setText("")
        self.labelTemp61.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp61.setObjectName("labelTemp61")
        self.verticalLayoutCielo61.addWidget(self.labelTemp61)
        self.gridLayout.addWidget(self.frameCielo61, 1, 13, 1, 1)
        self.frameCielo42 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo42.setObjectName("frameCielo42")
        self.verticalLayoutCielo42 = QtWidgets.QVBoxLayout(self.frameCielo42)
        self.verticalLayoutCielo42.setObjectName("verticalLayoutCielo42")
        self.labelHora42 = QtWidgets.QLabel(self.frameCielo42)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora42.setFont(font)
        self.labelHora42.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora42.setObjectName("labelHora42")
        self.verticalLayoutCielo42.addWidget(self.labelHora42)
        self.labelCielo42 = QtWidgets.QLabel(self.frameCielo42)
        self.labelCielo42.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo42.setText("")
        self.labelCielo42.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo42.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo42.setObjectName("labelCielo42")
        self.verticalLayoutCielo42.addWidget(self.labelCielo42)
        self.labelTemp42 = QtWidgets.QLabel(self.frameCielo42)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp42.setFont(font)
        self.labelTemp42.setText("")
        self.labelTemp42.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp42.setObjectName("labelTemp42")
        self.verticalLayoutCielo42.addWidget(self.labelTemp42)
        self.gridLayout.addWidget(self.frameCielo42, 1, 11, 1, 1)
        self.frameCielo21 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo21.setObjectName("frameCielo21")
        self.verticalLayoutCielo21 = QtWidgets.QVBoxLayout(self.frameCielo21)
        self.verticalLayoutCielo21.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayoutCielo21.setObjectName("verticalLayoutCielo21")
        self.labelHora21 = QtWidgets.QLabel(self.frameCielo21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora21.setFont(font)
        self.labelHora21.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora21.setObjectName("labelHora21")
        self.verticalLayoutCielo21.addWidget(self.labelHora21)
        self.labelCielo21 = QtWidgets.QLabel(self.frameCielo21)
        self.labelCielo21.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo21.setToolTip("")
        self.labelCielo21.setText("")
        self.labelCielo21.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo21.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo21.setObjectName("labelCielo21")
        self.verticalLayoutCielo21.addWidget(self.labelCielo21)
        self.labelTemp21 = QtWidgets.QLabel(self.frameCielo21)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp21.setFont(font)
        self.labelTemp21.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp21.setObjectName("labelTemp21")
        self.verticalLayoutCielo21.addWidget(self.labelTemp21)
        self.gridLayout.addWidget(self.frameCielo21, 1, 4, 1, 1)
        self.frameCielo24 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo24.setObjectName("frameCielo24")
        self.verticalLayoutCielo24 = QtWidgets.QVBoxLayout(self.frameCielo24)
        self.verticalLayoutCielo24.setObjectName("verticalLayoutCielo24")
        self.labelHora24 = QtWidgets.QLabel(self.frameCielo24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora24.setFont(font)
        self.labelHora24.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora24.setObjectName("labelHora24")
        self.verticalLayoutCielo24.addWidget(self.labelHora24)
        self.labelCielo24 = QtWidgets.QLabel(self.frameCielo24)
        self.labelCielo24.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo24.setText("")
        self.labelCielo24.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo24.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo24.setObjectName("labelCielo24")
        self.verticalLayoutCielo24.addWidget(self.labelCielo24)
        self.labelTemp24 = QtWidgets.QLabel(self.frameCielo24)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp24.setFont(font)
        self.labelTemp24.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp24.setObjectName("labelTemp24")
        self.verticalLayoutCielo24.addWidget(self.labelTemp24)
        self.gridLayout.addWidget(self.frameCielo24, 1, 7, 1, 1)
        self.frameCielo32 = QtWidgets.QFrame(self.framePrediccion)
        self.frameCielo32.setObjectName("frameCielo32")
        self.verticalLayoutCielo32 = QtWidgets.QVBoxLayout(self.frameCielo32)
        self.verticalLayoutCielo32.setObjectName("verticalLayoutCielo32")
        self.labelHora32 = QtWidgets.QLabel(self.frameCielo32)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHora32.setFont(font)
        self.labelHora32.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHora32.setObjectName("labelHora32")
        self.verticalLayoutCielo32.addWidget(self.labelHora32)
        self.labelCielo32 = QtWidgets.QLabel(self.frameCielo32)
        self.labelCielo32.setMinimumSize(QtCore.QSize(40, 40))
        self.labelCielo32.setText("")
        self.labelCielo32.setPixmap(QtGui.QPixmap(":/img/chanceflurries.png"))
        self.labelCielo32.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCielo32.setObjectName("labelCielo32")
        self.verticalLayoutCielo32.addWidget(self.labelCielo32)
        self.labelTemp32 = QtWidgets.QLabel(self.frameCielo32)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp32.setFont(font)
        self.labelTemp32.setText("")
        self.labelTemp32.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp32.setObjectName("labelTemp32")
        self.verticalLayoutCielo32.addWidget(self.labelTemp32)
        self.gridLayout.addWidget(self.frameCielo32, 1, 9, 1, 1)
        self.labelCota21 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota21.setFont(font)
        self.labelCota21.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota21.setObjectName("labelCota21")
        self.gridLayout.addWidget(self.labelCota21, 5, 4, 1, 1)
        self.labelCota24 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota24.setFont(font)
        self.labelCota24.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota24.setObjectName("labelCota24")
        self.gridLayout.addWidget(self.labelCota24, 5, 7, 1, 1)
        self.labelCota14 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota14.setFont(font)
        self.labelCota14.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota14.setObjectName("labelCota14")
        self.gridLayout.addWidget(self.labelCota14, 5, 3, 1, 1)
        self.labelCota31 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota31.setFont(font)
        self.labelCota31.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota31.setObjectName("labelCota31")
        self.gridLayout.addWidget(self.labelCota31, 5, 8, 1, 1)
        self.labelCota23 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota23.setFont(font)
        self.labelCota23.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota23.setObjectName("labelCota23")
        self.gridLayout.addWidget(self.labelCota23, 5, 6, 1, 1)
        self.labelCota41 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota41.setFont(font)
        self.labelCota41.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota41.setObjectName("labelCota41")
        self.gridLayout.addWidget(self.labelCota41, 5, 10, 1, 1)
        self.labelCota61 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota61.setFont(font)
        self.labelCota61.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota61.setObjectName("labelCota61")
        self.gridLayout.addWidget(self.labelCota61, 5, 13, 1, 1)
        self.labelCota42 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota42.setFont(font)
        self.labelCota42.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota42.setObjectName("labelCota42")
        self.gridLayout.addWidget(self.labelCota42, 5, 11, 1, 1)
        self.labelDia5 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelDia5.setFont(font)
        self.labelDia5.setStyleSheet("")
        self.labelDia5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDia5.setObjectName("labelDia5")
        self.gridLayout.addWidget(self.labelDia5, 0, 12, 1, 1)
        self.labelDia7 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelDia7.setFont(font)
        self.labelDia7.setStyleSheet("")
        self.labelDia7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDia7.setObjectName("labelDia7")
        self.gridLayout.addWidget(self.labelDia7, 0, 14, 1, 1)
        self.labelPrecip = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelPrecip.setFont(font)
        self.labelPrecip.setStyleSheet("")
        self.labelPrecip.setObjectName("labelPrecip")
        self.gridLayout.addWidget(self.labelPrecip, 2, 0, 1, 15)
        self.labelDia6 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelDia6.setFont(font)
        self.labelDia6.setStyleSheet("")
        self.labelDia6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDia6.setObjectName("labelDia6")
        self.gridLayout.addWidget(self.labelDia6, 0, 13, 1, 1)
        self.labelPrecip11 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip11.setFont(font)
        self.labelPrecip11.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip11.setObjectName("labelPrecip11")
        self.gridLayout.addWidget(self.labelPrecip11, 3, 0, 1, 1)
        self.labelPrecip21 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip21.setFont(font)
        self.labelPrecip21.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip21.setObjectName("labelPrecip21")
        self.gridLayout.addWidget(self.labelPrecip21, 3, 4, 1, 1)
        self.labelPrecip22 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip22.setFont(font)
        self.labelPrecip22.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip22.setObjectName("labelPrecip22")
        self.gridLayout.addWidget(self.labelPrecip22, 3, 5, 1, 1)
        self.labelPrecip12 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip12.setFont(font)
        self.labelPrecip12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip12.setObjectName("labelPrecip12")
        self.gridLayout.addWidget(self.labelPrecip12, 3, 1, 1, 1)
        self.labelPrecip14 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip14.setFont(font)
        self.labelPrecip14.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip14.setObjectName("labelPrecip14")
        self.gridLayout.addWidget(self.labelPrecip14, 3, 3, 1, 1)
        self.labelPrecip13 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip13.setFont(font)
        self.labelPrecip13.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip13.setObjectName("labelPrecip13")
        self.gridLayout.addWidget(self.labelPrecip13, 3, 2, 1, 1)
        self.labelPrecip32 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip32.setFont(font)
        self.labelPrecip32.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip32.setObjectName("labelPrecip32")
        self.gridLayout.addWidget(self.labelPrecip32, 3, 9, 1, 1)
        self.labelPrecip23 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip23.setFont(font)
        self.labelPrecip23.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip23.setObjectName("labelPrecip23")
        self.gridLayout.addWidget(self.labelPrecip23, 3, 6, 1, 1)
        self.labelPrecip24 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip24.setFont(font)
        self.labelPrecip24.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip24.setObjectName("labelPrecip24")
        self.gridLayout.addWidget(self.labelPrecip24, 3, 7, 1, 1)
        self.labelPrecip51 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip51.setFont(font)
        self.labelPrecip51.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip51.setObjectName("labelPrecip51")
        self.gridLayout.addWidget(self.labelPrecip51, 3, 12, 1, 1)
        self.labelPrecip42 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip42.setFont(font)
        self.labelPrecip42.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip42.setObjectName("labelPrecip42")
        self.gridLayout.addWidget(self.labelPrecip42, 3, 11, 1, 1)
        self.labelPrecip31 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip31.setFont(font)
        self.labelPrecip31.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip31.setObjectName("labelPrecip31")
        self.gridLayout.addWidget(self.labelPrecip31, 3, 8, 1, 1)
        self.labelPrecip61 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip61.setFont(font)
        self.labelPrecip61.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip61.setObjectName("labelPrecip61")
        self.gridLayout.addWidget(self.labelPrecip61, 3, 13, 1, 1)
        self.labelCota = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelCota.setFont(font)
        self.labelCota.setStyleSheet("")
        self.labelCota.setObjectName("labelCota")
        self.gridLayout.addWidget(self.labelCota, 4, 0, 1, 15)
        self.labelCota12 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota12.setFont(font)
        self.labelCota12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota12.setObjectName("labelCota12")
        self.gridLayout.addWidget(self.labelCota12, 5, 1, 1, 1)
        self.labelPrecip41 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip41.setFont(font)
        self.labelPrecip41.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip41.setObjectName("labelPrecip41")
        self.gridLayout.addWidget(self.labelPrecip41, 3, 10, 1, 1)
        self.labelCota11 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota11.setFont(font)
        self.labelCota11.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota11.setObjectName("labelCota11")
        self.gridLayout.addWidget(self.labelCota11, 5, 0, 1, 1)
        self.labelCota13 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota13.setFont(font)
        self.labelCota13.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota13.setObjectName("labelCota13")
        self.gridLayout.addWidget(self.labelCota13, 5, 2, 1, 1)
        self.labelCota22 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota22.setFont(font)
        self.labelCota22.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota22.setObjectName("labelCota22")
        self.gridLayout.addWidget(self.labelCota22, 5, 5, 1, 1)
        self.labelPrecip71 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrecip71.setFont(font)
        self.labelPrecip71.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecip71.setObjectName("labelPrecip71")
        self.gridLayout.addWidget(self.labelPrecip71, 3, 14, 1, 1)
        self.labelCota71 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCota71.setFont(font)
        self.labelCota71.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCota71.setObjectName("labelCota71")
        self.gridLayout.addWidget(self.labelCota71, 5, 14, 1, 1)
        self.labelMinMax5 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMinMax5.setFont(font)
        self.labelMinMax5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinMax5.setObjectName("labelMinMax5")
        self.gridLayout.addWidget(self.labelMinMax5, 7, 12, 1, 1)
        self.labelMinMax6 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMinMax6.setFont(font)
        self.labelMinMax6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinMax6.setObjectName("labelMinMax6")
        self.gridLayout.addWidget(self.labelMinMax6, 7, 13, 1, 1)
        self.labelMinMax = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelMinMax.setFont(font)
        self.labelMinMax.setStyleSheet("")
        self.labelMinMax.setObjectName("labelMinMax")
        self.gridLayout.addWidget(self.labelMinMax, 6, 0, 1, 15)
        self.labelViento11 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento11.setFont(font)
        self.labelViento11.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento11.setObjectName("labelViento11")
        self.gridLayout.addWidget(self.labelViento11, 9, 0, 1, 1)
        self.labelMinMax7 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMinMax7.setFont(font)
        self.labelMinMax7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinMax7.setObjectName("labelMinMax7")
        self.gridLayout.addWidget(self.labelMinMax7, 7, 14, 1, 1)
        self.labelViento = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelViento.setFont(font)
        self.labelViento.setStyleSheet("")
        self.labelViento.setObjectName("labelViento")
        self.gridLayout.addWidget(self.labelViento, 8, 0, 1, 15)
        self.labelViento12 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento12.setFont(font)
        self.labelViento12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento12.setObjectName("labelViento12")
        self.gridLayout.addWidget(self.labelViento12, 9, 1, 1, 1)
        self.labelViento14 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento14.setFont(font)
        self.labelViento14.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento14.setObjectName("labelViento14")
        self.gridLayout.addWidget(self.labelViento14, 9, 3, 1, 1)
        self.labelViento22 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento22.setFont(font)
        self.labelViento22.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento22.setObjectName("labelViento22")
        self.gridLayout.addWidget(self.labelViento22, 9, 5, 1, 1)
        self.labelViento13 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento13.setFont(font)
        self.labelViento13.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento13.setObjectName("labelViento13")
        self.gridLayout.addWidget(self.labelViento13, 9, 2, 1, 1)
        self.labelViento21 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento21.setFont(font)
        self.labelViento21.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento21.setObjectName("labelViento21")
        self.gridLayout.addWidget(self.labelViento21, 9, 4, 1, 1)
        self.labelViento24 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento24.setFont(font)
        self.labelViento24.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento24.setObjectName("labelViento24")
        self.gridLayout.addWidget(self.labelViento24, 9, 7, 1, 1)
        self.labelViento23 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento23.setFont(font)
        self.labelViento23.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento23.setObjectName("labelViento23")
        self.gridLayout.addWidget(self.labelViento23, 9, 6, 1, 1)
        self.labelViento32 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento32.setFont(font)
        self.labelViento32.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento32.setObjectName("labelViento32")
        self.gridLayout.addWidget(self.labelViento32, 9, 9, 1, 1)
        self.labelViento31 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento31.setFont(font)
        self.labelViento31.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento31.setObjectName("labelViento31")
        self.gridLayout.addWidget(self.labelViento31, 9, 8, 1, 1)
        self.labelViento61 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento61.setFont(font)
        self.labelViento61.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento61.setObjectName("labelViento61")
        self.gridLayout.addWidget(self.labelViento61, 9, 13, 1, 1)
        self.labelViento41 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento41.setFont(font)
        self.labelViento41.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento41.setObjectName("labelViento41")
        self.gridLayout.addWidget(self.labelViento41, 9, 10, 1, 1)
        self.labelViento51 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento51.setFont(font)
        self.labelViento51.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento51.setObjectName("labelViento51")
        self.gridLayout.addWidget(self.labelViento51, 9, 12, 1, 1)
        self.labelViento42 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento42.setFont(font)
        self.labelViento42.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento42.setObjectName("labelViento42")
        self.gridLayout.addWidget(self.labelViento42, 9, 11, 1, 1)
        self.labelViento71 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelViento71.setFont(font)
        self.labelViento71.setAlignment(QtCore.Qt.AlignCenter)
        self.labelViento71.setObjectName("labelViento71")
        self.gridLayout.addWidget(self.labelViento71, 9, 14, 1, 1)
        self.labelUv6 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUv6.setFont(font)
        self.labelUv6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUv6.setObjectName("labelUv6")
        self.gridLayout.addWidget(self.labelUv6, 11, 13, 1, 1)
        self.labelUv5 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUv5.setFont(font)
        self.labelUv5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUv5.setObjectName("labelUv5")
        self.gridLayout.addWidget(self.labelUv5, 11, 12, 1, 1)
        self.labelUv = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelUv.setFont(font)
        self.labelUv.setStyleSheet("")
        self.labelUv.setObjectName("labelUv")
        self.gridLayout.addWidget(self.labelUv, 10, 0, 1, 15)
        self.labelDia3 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelDia3.setFont(font)
        self.labelDia3.setStyleSheet("")
        self.labelDia3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDia3.setObjectName("labelDia3")
        self.gridLayout.addWidget(self.labelDia3, 0, 8, 1, 2)
        self.labelDia2 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelDia2.setFont(font)
        self.labelDia2.setStyleSheet("")
        self.labelDia2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDia2.setObjectName("labelDia2")
        self.gridLayout.addWidget(self.labelDia2, 0, 4, 1, 4)
        self.labelDia1 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelDia1.setFont(font)
        self.labelDia1.setStyleSheet("")
        self.labelDia1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDia1.setObjectName("labelDia1")
        self.gridLayout.addWidget(self.labelDia1, 0, 0, 1, 4)
        self.labelUv7 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUv7.setFont(font)
        self.labelUv7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUv7.setObjectName("labelUv7")
        self.gridLayout.addWidget(self.labelUv7, 11, 14, 1, 1)
        self.labelDia4 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelDia4.setFont(font)
        self.labelDia4.setStyleSheet("")
        self.labelDia4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDia4.setObjectName("labelDia4")
        self.gridLayout.addWidget(self.labelDia4, 0, 10, 1, 2)
        self.labelMinMax3 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMinMax3.setFont(font)
        self.labelMinMax3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinMax3.setObjectName("labelMinMax3")
        self.gridLayout.addWidget(self.labelMinMax3, 7, 8, 1, 2)
        self.labelMinMax2 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMinMax2.setFont(font)
        self.labelMinMax2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinMax2.setObjectName("labelMinMax2")
        self.gridLayout.addWidget(self.labelMinMax2, 7, 4, 1, 4)
        self.labelMinMax1 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMinMax1.setFont(font)
        self.labelMinMax1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinMax1.setObjectName("labelMinMax1")
        self.gridLayout.addWidget(self.labelMinMax1, 7, 0, 1, 4)
        self.labelUv3 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUv3.setFont(font)
        self.labelUv3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUv3.setObjectName("labelUv3")
        self.gridLayout.addWidget(self.labelUv3, 11, 8, 1, 2)
        self.labelUv2 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUv2.setFont(font)
        self.labelUv2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUv2.setObjectName("labelUv2")
        self.gridLayout.addWidget(self.labelUv2, 11, 4, 1, 4)
        self.labelUv1 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUv1.setFont(font)
        self.labelUv1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUv1.setObjectName("labelUv1")
        self.gridLayout.addWidget(self.labelUv1, 11, 0, 1, 4)
        self.labelMinMax4 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMinMax4.setFont(font)
        self.labelMinMax4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinMax4.setObjectName("labelMinMax4")
        self.gridLayout.addWidget(self.labelMinMax4, 7, 10, 1, 2)
        self.labelUv4 = QtWidgets.QLabel(self.framePrediccion)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUv4.setFont(font)
        self.labelUv4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUv4.setObjectName("labelUv4")
        self.gridLayout.addWidget(self.labelUv4, 11, 10, 1, 2)
        self.verticalLayout.addWidget(self.framePrediccion)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MeteoCloud"))
        self.labelFiltro.setText(_translate("MainWindow", "Filtrar población"))
        self.pushButtonFiltro.setText(_translate("MainWindow", "Filtrar"))
        __sortingEnabled = self.listWidgetFiltro.isSortingEnabled()
        self.listWidgetFiltro.setSortingEnabled(False)
        item = self.listWidgetFiltro.item(0)
        item.setText(_translate("MainWindow", "safsaf"))
        item = self.listWidgetFiltro.item(1)
        item.setText(_translate("MainWindow", "sa"))
        item = self.listWidgetFiltro.item(2)
        item.setText(_translate("MainWindow", "fsad"))
        item = self.listWidgetFiltro.item(3)
        item.setText(_translate("MainWindow", "fs"))
        item = self.listWidgetFiltro.item(4)
        item.setText(_translate("MainWindow", "adf"))
        item = self.listWidgetFiltro.item(5)
        item.setText(_translate("MainWindow", "ad"))
        item = self.listWidgetFiltro.item(6)
        item.setText(_translate("MainWindow", "fd"))
        item = self.listWidgetFiltro.item(7)
        item.setText(_translate("MainWindow", "f"))
        item = self.listWidgetFiltro.item(8)
        item.setText(_translate("MainWindow", "das"))
        item = self.listWidgetFiltro.item(9)
        item.setText(_translate("MainWindow", "fd"))
        item = self.listWidgetFiltro.item(10)
        item.setText(_translate("MainWindow", "af"))
        item = self.listWidgetFiltro.item(11)
        item.setText(_translate("MainWindow", "das"))
        item = self.listWidgetFiltro.item(12)
        item.setText(_translate("MainWindow", "f"))
        item = self.listWidgetFiltro.item(13)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidgetFiltro.item(14)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidgetFiltro.setSortingEnabled(__sortingEnabled)
        self.labelPoblacion.setText(_translate("MainWindow", "Población"))
        self.pushButtonPoblacion.setText(_translate("MainWindow", "Favorita"))
        self.frameCielo13.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora13.setText(_translate("MainWindow", "12-18 h"))
        self.labelTemp13.setText(_translate("MainWindow", "15ºC"))
        self.frameCielo12.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora12.setText(_translate("MainWindow", "06-12 h"))
        self.labelTemp12.setText(_translate("MainWindow", "18ºC"))
        self.frameCielo11.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora11.setText(_translate("MainWindow", "00-06 h"))
        self.labelTemp11.setText(_translate("MainWindow", "20ºC"))
        self.frameCielo23.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora23.setText(_translate("MainWindow", "12-18 h"))
        self.labelTemp23.setText(_translate("MainWindow", "15ºC"))
        self.frameCielo31.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora31.setText(_translate("MainWindow", "00-12 h"))
        self.labelCota51.setText(_translate("MainWindow", "350"))
        self.labelCota51.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota32.setText(_translate("MainWindow", "0"))
        self.labelCota32.setProperty("type", _translate("MainWindow", "value"))
        self.frameCielo41.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora41.setText(_translate("MainWindow", "00-12 h"))
        self.frameCielo14.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora14.setText(_translate("MainWindow", "18-24 h"))
        self.labelTemp14.setText(_translate("MainWindow", "10ºC"))
        self.frameCielo71.setProperty("type", _translate("MainWindow", "value"))
        self.frameCielo22.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora22.setText(_translate("MainWindow", "06-12 h"))
        self.labelTemp22.setText(_translate("MainWindow", "18ºC"))
        self.frameCielo51.setProperty("type", _translate("MainWindow", "value"))
        self.frameCielo61.setProperty("type", _translate("MainWindow", "value"))
        self.frameCielo42.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora42.setText(_translate("MainWindow", "12-24 h"))
        self.frameCielo21.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora21.setText(_translate("MainWindow", "00-06 h"))
        self.labelTemp21.setText(_translate("MainWindow", "20ºC"))
        self.frameCielo24.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora24.setText(_translate("MainWindow", "18-24 h"))
        self.labelTemp24.setText(_translate("MainWindow", "10ºC"))
        self.frameCielo32.setProperty("type", _translate("MainWindow", "value"))
        self.labelHora32.setText(_translate("MainWindow", "12-24 h"))
        self.labelCota21.setText(_translate("MainWindow", "500"))
        self.labelCota21.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota24.setText(_translate("MainWindow", "0"))
        self.labelCota24.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota14.setText(_translate("MainWindow", "300"))
        self.labelCota14.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota31.setText(_translate("MainWindow", "0"))
        self.labelCota31.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota23.setText(_translate("MainWindow", "0"))
        self.labelCota23.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota41.setText(_translate("MainWindow", "200"))
        self.labelCota41.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota61.setText(_translate("MainWindow", "400"))
        self.labelCota61.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota42.setText(_translate("MainWindow", "1000"))
        self.labelCota42.setProperty("type", _translate("MainWindow", "value"))
        self.labelDia5.setText(_translate("MainWindow", "Vie 5"))
        self.labelDia5.setProperty("type", _translate("MainWindow", "header"))
        self.labelDia7.setText(_translate("MainWindow", "Dom 7"))
        self.labelDia7.setProperty("type", _translate("MainWindow", "header"))
        self.labelPrecip.setText(_translate("MainWindow", "Probabilidad de precipitación"))
        self.labelPrecip.setProperty("type", _translate("MainWindow", "header"))
        self.labelDia6.setText(_translate("MainWindow", "Sab 6"))
        self.labelDia6.setProperty("type", _translate("MainWindow", "header"))
        self.labelPrecip11.setText(_translate("MainWindow", "20%"))
        self.labelPrecip11.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip21.setText(_translate("MainWindow", "20%"))
        self.labelPrecip21.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip22.setText(_translate("MainWindow", "20%"))
        self.labelPrecip22.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip12.setText(_translate("MainWindow", "20%"))
        self.labelPrecip12.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip14.setText(_translate("MainWindow", "20%"))
        self.labelPrecip14.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip13.setText(_translate("MainWindow", "20%"))
        self.labelPrecip13.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip32.setText(_translate("MainWindow", "20%"))
        self.labelPrecip32.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip23.setText(_translate("MainWindow", "20%"))
        self.labelPrecip23.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip24.setText(_translate("MainWindow", "20%"))
        self.labelPrecip24.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip51.setText(_translate("MainWindow", "20%"))
        self.labelPrecip51.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip42.setText(_translate("MainWindow", "20%"))
        self.labelPrecip42.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip31.setText(_translate("MainWindow", "20%"))
        self.labelPrecip31.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip61.setText(_translate("MainWindow", "20%"))
        self.labelPrecip61.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota.setText(_translate("MainWindow", "Cota de nieve (m)"))
        self.labelCota.setProperty("type", _translate("MainWindow", "header"))
        self.labelCota12.setText(_translate("MainWindow", "400"))
        self.labelCota12.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip41.setText(_translate("MainWindow", "20%"))
        self.labelPrecip41.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota11.setText(_translate("MainWindow", "200"))
        self.labelCota11.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota13.setText(_translate("MainWindow", "200"))
        self.labelCota13.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota22.setText(_translate("MainWindow", "200"))
        self.labelCota22.setProperty("type", _translate("MainWindow", "value"))
        self.labelPrecip71.setText(_translate("MainWindow", "20%"))
        self.labelPrecip71.setProperty("type", _translate("MainWindow", "value"))
        self.labelCota71.setText(_translate("MainWindow", "0"))
        self.labelCota71.setProperty("type", _translate("MainWindow", "value"))
        self.labelMinMax5.setText(_translate("MainWindow", "19 / 25"))
        self.labelMinMax5.setProperty("type", _translate("MainWindow", "value"))
        self.labelMinMax6.setText(_translate("MainWindow", "18 / 21"))
        self.labelMinMax6.setProperty("type", _translate("MainWindow", "value"))
        self.labelMinMax.setText(_translate("MainWindow", "Temperaturas mínima y máxima (ºC)"))
        self.labelMinMax.setProperty("type", _translate("MainWindow", "header"))
        self.labelViento11.setText(_translate("MainWindow", "20"))
        self.labelViento11.setProperty("type", _translate("MainWindow", "value"))
        self.labelMinMax7.setText(_translate("MainWindow", "20 / 25"))
        self.labelMinMax7.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento.setText(_translate("MainWindow", "Dirección y velocidad del viento (km/h)"))
        self.labelViento.setProperty("type", _translate("MainWindow", "header"))
        self.labelViento12.setText(_translate("MainWindow", "20"))
        self.labelViento12.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento14.setText(_translate("MainWindow", "20"))
        self.labelViento14.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento22.setText(_translate("MainWindow", "20"))
        self.labelViento22.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento13.setText(_translate("MainWindow", "20"))
        self.labelViento13.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento21.setText(_translate("MainWindow", "20"))
        self.labelViento21.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento24.setText(_translate("MainWindow", "20"))
        self.labelViento24.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento23.setText(_translate("MainWindow", "20"))
        self.labelViento23.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento32.setText(_translate("MainWindow", "20"))
        self.labelViento32.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento31.setText(_translate("MainWindow", "20"))
        self.labelViento31.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento61.setText(_translate("MainWindow", "20"))
        self.labelViento61.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento41.setText(_translate("MainWindow", "20"))
        self.labelViento41.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento51.setText(_translate("MainWindow", "20"))
        self.labelViento51.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento42.setText(_translate("MainWindow", "20"))
        self.labelViento42.setProperty("type", _translate("MainWindow", "value"))
        self.labelViento71.setText(_translate("MainWindow", "20"))
        self.labelViento71.setProperty("type", _translate("MainWindow", "value"))
        self.labelUv6.setText(_translate("MainWindow", "2"))
        self.labelUv6.setProperty("type", _translate("MainWindow", "value"))
        self.labelUv5.setText(_translate("MainWindow", "4"))
        self.labelUv5.setProperty("type", _translate("MainWindow", "value"))
        self.labelUv.setText(_translate("MainWindow", "Índice ultravioleta máximo"))
        self.labelUv.setProperty("type", _translate("MainWindow", "header"))
        self.labelDia3.setText(_translate("MainWindow", "Mié 3"))
        self.labelDia3.setProperty("type", _translate("MainWindow", "header"))
        self.labelDia2.setText(_translate("MainWindow", "Mar 2"))
        self.labelDia2.setProperty("type", _translate("MainWindow", "header"))
        self.labelDia1.setText(_translate("MainWindow", "Lun 1"))
        self.labelDia1.setProperty("type", _translate("MainWindow", "header"))
        self.labelUv7.setText(_translate("MainWindow", "0"))
        self.labelUv7.setProperty("type", _translate("MainWindow", "value"))
        self.labelDia4.setText(_translate("MainWindow", "Jue 4"))
        self.labelDia4.setProperty("type", _translate("MainWindow", "header"))
        self.labelMinMax3.setText(_translate("MainWindow", "15 / 23"))
        self.labelMinMax3.setProperty("type", _translate("MainWindow", "value"))
        self.labelMinMax2.setText(_translate("MainWindow", "16 / 26"))
        self.labelMinMax2.setProperty("type", _translate("MainWindow", "value"))
        self.labelMinMax1.setText(_translate("MainWindow", "10 / 20"))
        self.labelMinMax1.setProperty("type", _translate("MainWindow", "value"))
        self.labelUv3.setText(_translate("MainWindow", "4"))
        self.labelUv3.setProperty("type", _translate("MainWindow", "value"))
        self.labelUv2.setText(_translate("MainWindow", "2"))
        self.labelUv2.setProperty("type", _translate("MainWindow", "value"))
        self.labelUv1.setText(_translate("MainWindow", "4"))
        self.labelUv1.setProperty("type", _translate("MainWindow", "value"))
        self.labelMinMax4.setText(_translate("MainWindow", "15 / 20"))
        self.labelMinMax4.setProperty("type", _translate("MainWindow", "value"))
        self.labelUv4.setText(_translate("MainWindow", "4"))
        self.labelUv4.setProperty("type", _translate("MainWindow", "value"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

